DROP TABLE IF EXISTS USUARIOS, HOROSCOPO;

CREATE TABLE horoscopo
(
    ANIMAL       VARCHAR(30),
    FECHA_INICIO DATE,
    FECHA_FIN    DATE
);

CREATE TABLE usuarios
(
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(30),
    USERNAME VARCHAR(30),
    EMAIL VARCHAR(30),
    FECHA_NACIMIENTO DATE,
    PASSWORD VARCHAR(30),
    ANIMAL VARCHAR(30)
);

INSERT INTO usuarios (ID, NOMBRE, USERNAME, EMAIL, FECHA_NACIMIENTO, PASSWORD, ANIMAL)
VALUES (12, 'admin', 'admin', 'admin@gmail.com', '1980-01-01', 'admin', 'León');

INSERT INTO usuarios (ID, NOMBRE, USERNAME, EMAIL, FECHA_NACIMIENTO, PASSWORD, ANIMAL)
VALUES (2, 'Juan Pérez', 'juanp', 'juanperez@gmail.com', '1990-05-15', 'juan123', 'Tigre');
